export const currentLearningAndFutureGoals = [
  {
    id: 1,
    src: 'https://fastly.picsum.photos/id/134/536/354.jpg?hmac=GqngKpJ4MNwWb4KIR11yok3yVmLUyrVIYAX2E37h4dA',
    alt: 'THREE.JS',
    description: 'Write your description here',
  },
  {
    id: 2,
    src: 'https://fastly.picsum.photos/id/134/536/354.jpg?hmac=GqngKpJ4MNwWb4KIR11yok3yVmLUyrVIYAX2E37h4dA',
    alt: 'SHADERS (GLSL)',
    description: 'Write your description here',
  },
  {
    id: 3,
    src: 'https://fastly.picsum.photos/id/134/536/354.jpg?hmac=GqngKpJ4MNwWb4KIR11yok3yVmLUyrVIYAX2E37h4dA',
    alt: 'NEXT.JS',
    description: 'Write your description here',
  },
  {
    id: 4,
    src: 'https://fastly.picsum.photos/id/134/536/354.jpg?hmac=GqngKpJ4MNwWb4KIR11yok3yVmLUyrVIYAX2E37h4dA',
    alt: 'NODE.JS & EXPRESS.JS',
    description: 'Write your description here',
  },
  {
    id: 5,
    src: 'https://fastly.picsum.photos/id/134/536/354.jpg?hmac=GqngKpJ4MNwWb4KIR11yok3yVmLUyrVIYAX2E37h4dA',
    alt: 'MONGODB',
    description: 'Write your description here',
  },
  {
    id: 6,
    src: 'https://fastly.picsum.photos/id/134/536/354.jpg?hmac=GqngKpJ4MNwWb4KIR11yok3yVmLUyrVIYAX2E37h4dA',
    alt: 'TYPESCRIPT',
    description: 'Write your description here',
  },
  {
    id: 7,
    src: 'https://fastly.picsum.photos/id/134/536/354.jpg?hmac=GqngKpJ4MNwWb4KIR11yok3yVmLUyrVIYAX2E37h4dA',
    alt: 'REACT THREE FIBER',
    description: 'Write your description here',
  },
  {
    id: 8,
    src: 'https://fastly.picsum.photos/id/134/536/354.jpg?hmac=GqngKpJ4MNwWb4KIR11yok3yVmLUyrVIYAX2E37h4dA',
    alt: 'ANGULAR.JS & VUE.JS',
    description: 'Write your description here',
  },
  {
    id: 9,
    src: 'https://fastly.picsum.photos/id/134/536/354.jpg?hmac=GqngKpJ4MNwWb4KIR11yok3yVmLUyrVIYAX2E37h4dA',
    alt: 'NUXT.JS, SVELTE & SVELTE KIT',
    description: 'Write your description here',
  },
  {
    id: 10,
    src: 'https://fastly.picsum.photos/id/134/536/354.jpg?hmac=GqngKpJ4MNwWb4KIR11yok3yVmLUyrVIYAX2E37h4dA',
    alt: 'NEST.JS',
    description: 'Write your description here',
  },
  {
    id: 11,
    src: 'https://fastly.picsum.photos/id/134/536/354.jpg?hmac=GqngKpJ4MNwWb4KIR11yok3yVmLUyrVIYAX2E37h4dA',
    alt: 'PYTHON & AI ENGINEERING',
    description: 'Write your description here',
  },
  {
    id: 12,
    src: 'https://fastly.picsum.photos/id/134/536/354.jpg?hmac=GqngKpJ4MNwWb4KIR11yok3yVmLUyrVIYAX2E37h4dA',
    alt: 'WEB 3 & BLOCKCHAIN',
    description: 'Write your description here',
  },
  {
    id: 13,
    src: 'https://fastly.picsum.photos/id/134/536/354.jpg?hmac=GqngKpJ4MNwWb4KIR11yok3yVmLUyrVIYAX2E37h4dA',
    alt: 'VectorDB, LLMs, Generative AI',
    description: 'Write your description here',
  },
];