export const skills = [
	{
		id: 1,
		skills: 'HTML, CSS, SCSS',
		description: 'Structure & Styling',
		imgSrc: '/skills/html.png',
		class: 'bg-red-100 p-2 rounded',
	},
	{
		id: 2,
		skills: 'tailwind css, bootstrap, styled components',
		description: 'Modern styling',
		imgSrc: '/skills/tailwindcss.png',
		class: 'bg-cyan-50 p-2 rounded',
	},
	{
		id: 3,
		skills: 'javascript, typescript',
		description: 'Programming Languages',
		imgSrc: '/skills/javascript.png',
		class: 'bg-amber-100 p-2 rounded',
	},
	{
		id: 4,
		skills: 'react, next.js',
		description: 'UI Library & Frameworks',
		imgSrc: '/skills/react.png',
		class: 'bg-sky-50 p-2 rounded',
	},
	{
		id: 5,
		skills: 'React router, RTK, Redux Query, Zustand',
		description: 'Routing & State Management',
		imgSrc: '/skills/redux.png',
		class: 'bg-purple-50 p-2 rounded',
	},
	{
		id: 6,
		skills: 'gsap, framer motion',
		description: 'Animation & Interaction',
		imgSrc: '/skills/gsap.png',
		class: 'bg-lime-100 p-2 rounded',
	},
	{
		id: 7,
		skills: 'git, github',
		description: 'Version Control',
		imgSrc: '/skills/git.png',
		class: 'bg-rose-100 p-2 rounded',
	},
	{
		id: 8,
		skills: 'node.js, express.js',
		description: 'Runtime & Framework',
		imgSrc: '/skills/node.png',
		class: 'bg-green-100 p-2 rounded',
	},
	{
		id: 9,
		skills: 'mongodb, mongoose',
		description: 'Database & ODM',
		imgSrc: '/skills/mongodb.png',
		class: 'bg-green-100 p-2 rounded',
	},
	{
		id: 10,
		skills: 'socket.io, webrtc',
		description: 'Real-time Communication',
		imgSrc: '/skills/socketio.png',
		class: 'bg-zinc-100 p-2 rounded',
	},
	{
		id: 11,
		skills: 'drupal, wordpress',
		description: 'CMS',
		imgSrc: '/skills/drupal.png',
		class: 'bg-sky-50 p-2 rounded',
	},
	{
		id: 12,
		skills: 'postman, figma, vscode',
		description: 'Dev Tools',
		imgSrc: '/skills/vscode.png',
		class: 'bg-sky-50 p-2 rounded',
	},
	{
		id: 13,
		skills: 'Edge, Chrome, Firefox',
		description: 'AI Debugging',
		imgSrc: '/skills/edge.png',
		class: 'bg-emerald-50 p-2 rounded',
	},
];
